//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XYOL.MvcWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public string Id { get; set; }
        public string Title { get; set; }
        public string MainContent { get; set; }
        public string Contributor { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string VideoPath { get; set; }
    }
}
