//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XYOL.MvcWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public System.Guid Id { get; set; }
        public string Username { get; set; }
        public Nullable<int> Age { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string Password { get; set; }
        public string Realname { get; set; }
        public string Department { get; set; }
    }
}
